[package]
name = "platform-mock"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
remote-protocol = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
